# Unit 1 - files

read(n)

In [3]:
f = open("data.txt", 'r')

s1 = f.read(10)
s2 = f.read(5)
s3 = f.read()

print(s1, s2, s3, sep="\n\n")

f.close()

india is m

y cou

ntry and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.
I shall always strive to be worthy of it.
I shall give respect.



In [5]:
f = open("data.txt", 'r')

s1 = f.read()
s2 = f.read(10)
s3 = f.read(5)

print(s1, s2, s3, sep="\n -next- \n")

f.close()

india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.
I shall always strive to be worthy of it.
I shall give respect.

 -next- 

 -next- 



readline(n)

In [6]:
f = open("data.txt", 'r')

l1 = f.readline()
l2 = f.readline()
l3 = f.readline(10)

print(l1, l2, l3, sep='\n')

f.close()

india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.

I shall always strive to be worthy of it.

I shall gi


#### read line by line using readline

In [8]:
f = open("data.txt", "r")

s = f.readline()
while s:
    print(s) # print(s, end="") for lines without space in between them
    s = f.readline()

f.close()

india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.

I shall always strive to be worthy of it.

I shall give respect.



#### read line by line using for loop

In [9]:
f = open("data.txt", 'r')

for line in f:
    print(line)
    
f.close()

india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.

I shall always strive to be worthy of it.

I shall give respect.



#### size without using EOL or blank lines

In [11]:
f = open("data.txt", 'r')

s, ts = 0, 0
line = f.readline()
while line:
    ts += len(line)
    s += len(line.strip())
    line = f.readline() # ****************************

print(s, ts)
f.close()

190 193


### readlines()

In [13]:
f = open("data.txt", 'r')

lines = f.readlines()
print(lines, lines[0], lines[-1], sep='\n')

f.close()

['india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.\n', 'I shall always strive to be worthy of it.\n', 'I shall give respect.\n']
india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.

I shall give respect.



#### size of file in bytes

In [15]:
f = open("data.txt", 'r')

print(len(f.read()))

f.close()

193


#### no. of lines in files

In [16]:
f = open("data.txt", 'r')

print(len(f.readlines()))

f.close()

3


#### write to files

In [21]:
f = open("student.txt", 'w')

name = "deven"
f.write(name)
f.write('\n')
f.write(name)
f.write('\n')

f.close()

f = open("student.txt", 'r')
print(f.read())
f.close()

deven
deven



append to files

In [22]:
f = open("student.txt", 'a')

name = "arpita"
f.write(name)
f.write('\n')
f.write(name)
f.write('\n')

f.close()

f = open("student.txt", 'r')
print(f.read())
f.close()

deven
deven
arpita
arpita



#### writelines

In [23]:
f = open("student.txt", 'w')

names = ["deven\n", "arpita\n", "abc\n"] # \n is important
f.writelines(names)

f.close()

f = open("student.txt", 'r')
print(f.read())
f.close()

deven
arpita
abc



#### seek( offset, whence=0 ) for text files

In [25]:
f = open("data.txt", "r")

f.seek(10) # whence = 0, starting, only possible to move from beg
print(f.tell(), f.readline())

# these two also possible, stay in current pos, and move to end

f.seek(0, 1)

f.seek(0, 2)

f.close()

10 y country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.



#### seek( offset, whence=0 ) for binary files

In [26]:
f = open("data.txt", "rb")

f.seek(15)
print(f.tell(), f.readline())

f.seek(10, 1)
print(f.tell(), f.readline())

f.seek(-15, 2)
print(f.tell(), f.readline())

f.close()

15 b'ntry and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.\r\n'
140 b'ways strive to be worthy of it.\r\n'
181 b'give respect.\r\n'


### serialization

#### serialization with byte_object b""

In [27]:
import pickle

abc = {1: 'a', 2: 'b', 3: 'c'}
abc_serial = pickle.dumps(abc)

q = pickle.loads(abc_serial)
print(q)

{1: 'a', 2: 'b', 3: 'c'}


#### serialization with files

In [29]:
import pickle

abc = {1: 'a', 2: 'b', 3: 'c'}

with open("data2.pickle", "wb") as f:
    pickle.dump(abc, f, pickle.HIGHEST_PROTOCOL)
    
with open("data2.pickle", "rb") as f:
    q = pickle.load(f)
print(q)

{1: 'a', 2: 'b', 3: 'c'}


#### serialization of a custom class

In [32]:
import pickle

class example_class:
    
    def __init__(self):
        self.n = 35
        self.s = "abc"
        self.l = [1, 2, 3]
        self.d = {'a': 1, 'b': 2}
        self.t = (3, 9)
        
obj = example_class()
obj_s = pickle.dumps(obj)

with open("data2.pickle", "wb") as f:
    pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

obj.d = None
print(obj, obj.d)

obj2 = pickle.loads(obj_s)
print(obj2, obj2.d)
    
with open("data2.pickle", "rb") as f:
    q = pickle.load(f)
    
print(q, q.d)

<__main__.example_class object at 0x000001C5805C25E0> None
<__main__.example_class object at 0x000001C5805DF250> {'a': 1, 'b': 2}
<__main__.example_class object at 0x000001C5805C2D60> {'a': 1, 'b': 2}


#### seek serialization assignment

In [38]:
f = open("data.txt", "rb")

print(f.read(), end="\n\n\n")

f.seek(-5, 2)
print(f.read()) # only 5 bytes

f.seek(0, 2) # end of file ******************************
print(f.read())

f.seek(-1, 2) # last char of file ******************************
print(f.read())

f.seek(10, 0) # consuming 10 bytes from beg, so at 11th loc
# but if they ask 10th loc from begining do this
print(f.read())

f.close()

b'india is my country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.\r\nI shall always strive to be worthy of it.\r\nI shall give respect.\r\n'


b'ct.\r\n'
b''
b'\n'
b'y country and all indians are my brothers and sisters. I love my country and i am proud of its rich and vary heritage.\r\nI shall always strive to be worthy of it.\r\nI shall give respect.\r\n'


#### 5) Implement a program to copy one python script into another by removing all the comment lines from the source file to destination file.

In [40]:
with open("src.txt", 'r') as rf:
    with open("dest.txt", 'w') as wf:
        
        for line in rf:
            if not line.strip().startswith("#"):
                wf.write(line)
                
with open("src.txt", 'r') as f:
    print(f.read())
                
with open("dest.txt", 'r') as f:
    print(f.read())

# welcome to this first program
print("Tony Stark created the Arc Reactor inside a cave")
a=5
print(f'The value of a is: {a}')
# program end

print("Tony Stark created the Arc Reactor inside a cave")
a=5
print(f'The value of a is: {a}')



#### 1) Write a program to enter the following records in a binary file:
     
Item No integer
  
Item_Name string
     
Qty integer

Price float

Number of records to be
entered should be accepted from the user. Read the file to display the records
in the following format:

Item No:

Item Name :

Quantity:

Price per item:

Amount: ( to be calculated as Price * Qty)

In [49]:
class Item:
    
    def __init__(self, no, name, qty, price):
        self.no = no
        self.name = name
        self.qty = qty
        self.price = price
        self.amount = price * qty
    
    def __str__(self): # don't do this in exam do print_item() function
        return '\n'.join([
            "Item No.: " + str(self.no),
            "Item Name: " + self.name,
            "Qty: " + str(self.qty),
            "Price: " + str(self.price),
            "Amount: " + str(self.amount)
        ])
    
    def print_item(self):
        print(self.no, self.name, self.qty, self.price, self.amount)
    

In [51]:
n = int(input("Enter no. of records to be entered: "))
lst = []
for i in range(n):
    obj = Item(i, "d"+str(i), 10*i, 100*i) # accept these also from user, 
    # maybe write a function to accept it from user... 
    lst.append(obj)

Enter no. of records to be entered: 5


In [52]:
import pickle

with open("items.dat", "wb") as f:
    for item in lst:
        pickle.dump(item, f) # highest protocol
        
with open("items.dat", "rb") as f:
    for item in lst:
        a = pickle.load(f)
        a.print_item()

0 d0 0 0 0
1 d1 10 100 1000
2 d2 20 200 4000
3 d3 30 300 9000
4 d4 40 400 16000


## 2) Write a program to accept string/sentences from the user till the user enters “END” to. Save the data in a text file and then display only those sentences which begin with an uppercase alphabet

In [54]:
with open("sentences.txt", "w") as f:
    
    sentence = input("Enter sentence: ")
    while sentence != "END":
        f.write(sentence + "\n") # \n VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVvvvimp
        sentence = input("Enter sentence: ")
    
with open("sentences.txt", "r") as f:
    print("Output: ")
    for sentence in f:
        if sentence[0].isupper():
            print(sentence, end="") # end="" coz the sentence already has \n

Enter sentence: Ab
Enter sentence: END
Output: 
Ab


#### 3) Write the file mode that will be used for opening the following files. Also, write the Python statements to open the following files:
a text file “example.txt” in both read and write mode

In [55]:
f = open("sentences.txt", "w+")
print("no error")
# w+ read and write both and create file if not exist
f.close()

no error


In [59]:
f = open("data.txt", 'r')

d = {}
for char in f.read():
    if char in d:
        d[char] += 1
    else:
        d[char] = 0
        
print(d)
        
f.close()

{'i': 12, 'n': 8, 'd': 6, 'a': 14, ' ': 35, 's': 11, 'm': 3, 'y': 7, 'c': 3, 'o': 8, 'u': 2, 't': 10, 'r': 12, 'l': 7, 'e': 10, 'b': 1, 'h': 5, '.': 3, 'I': 2, 'v': 3, 'p': 1, 'f': 1, 'g': 1, '\n': 2, 'w': 1}


### 5) Implement a python program to validate a mobile number. The number should start with 7, 8 or 9 followed by 9 digits.

In [60]:
import re

n = input("Enter 10 digit mobile number: ")
if re.match(r'[789]\d{9}', n):
    print("Number is correct")
else:
    print("Number is not correct")

Enter 10 digit mobile number: 7123456890
Number is correct


### exam papers

In [68]:
# 1) a)
tf = open("c.txt", "w+") # 1 w+
tf.write("Line 1\n")
tf.write("This is line 2\n")
tf.write("That makes this line 3\n") # 2 ""
lines = ["L1\n", "L2\n", "L3\n"] # 3 \n 4 ; 
tf.writelines(lines)
# a = tf.read()
# print(a)  # only these two lines won't work
tf.seek(0, 0) # 5 missing *****************************************
a = tf.read()
print(a)
tf.close()

Line 1
This is line 2
That makes this line 3
L1
L2
L3



In [69]:
# 2) comming program top

In [73]:
# 3) obj serial top

### Write a python program to reverse the content of a file and store it in another file

In [74]:
# 1) a)
with open("data.txt", 'r') as rf:
    with open("writefile.txt", 'w') as wf:
        data = rf.read()
        data = data[::-1]
        wf.write(data)

In [75]:
# 1) b) easy, show for dict obj and an list obj using files

# Unit 2

In [1]:
import sqlite3

con = sqlite3.connect("customer.db")
cur = con.cursor()

cur.execute("""
    create table customer(
    first_name text,
    last_name text,
    email text)
""")

con.commit()
con.close()

In [19]:
import sqlite3

con = sqlite3.connect("customer.db")
cur = con.cursor()

# cur.execute("delete from customer")
# # IMPORTANT, MAKE SURE TO USE ' ' INSIDE " "
# cur.execute("insert into customer values ('Tim', 'Smith', 'tim@code.com')")
# cur.execute("insert into customer values (?, ?, ?)", 
#             ['Mary', 'Brown', 'mary@code.com'])

# customers = [
#     ('wes', 'brown', 'wes@code.com'),
#     ('raju', 'k', 'raju@code.com'),
#     ('ravi', 'k', 'ravi@code.com')
# ]
# cur.executemany("insert into customer values (?, ?, ?)", customers)

# cur.execute("select * from customer")
# print(cur.fetchone())
# print(cur.fetchmany(2))
# print(cur.fetchall())

# cur.execute("select rowid, * from customer")
# print(cur.fetchall())

# # MAKE SURE TO USE ' '  INSIDE " "
# cur.execute("select rowid, * from customer where last_name='k'")
# print(cur.fetchall())

# # % for zero - multiple, _ for one single char
# cur.execute("select rowid, * from customer where last_name LIKE 'br%'")
# print(cur.fetchall())

# cur.execute("update customer set first_name='Bob' WHERE last_name='Smith'")

# cur.execute("update customer set first_name='Tim' where rowid=1")

# cur.execute("delete from customer where rowid=5")

# # when doing order by rowid, do select rowid, *, so that u can see the change
# # happening
# cur.execute("select rowid, * from customer order by rowid desc limit 2")
# print(cur.fetchall())

cur.execute("select rowid, * from customer")
print(cur.fetchall())

con.commit()
con.close()

[(1, 'Tim', 'Smith', 'tim@code.com'), (2, 'Mary', 'Brown', 'mary@code.com'), (3, 'wes', 'brown', 'wes@code.com'), (4, 'raju', 'k', 'raju@code.com')]


### assignment questions

1) Create a python program on the scenario given below: Create an Employee table with attributes such as emp_ssn, emp_name, emp_category, gross_sal, basic_sal. Insert atleast three values in to the database. Demonstrate the database concepts for the following scenario: A company management wants to compute the net salary of each group of employee based on the category of the employee such as Category A, Category B, Category C. Compute the net salary based on the following table.
        

In [4]:
import sqlite3
con = sqlite3.connect("xyzcompany.db")
cur = con.cursor()

In [5]:
cur.execute("""
    create table employee(
        ssn integer primary key,
        name text, 
        category text, 
        gross_sal real,
        basic_sal real
    )
""")

In [7]:
employees = [
    (1, "Rohan", 'A', "NULL", 1000),
    (2, "Mohan", 'B', "NULL", 2000),
    (3, "Sohan", 'C', "NULL", 3000)
]
cur.executemany("insert into employee values (?, ?, ?, ?, ?)", employees)

In [8]:
cur.execute("select * from employee")
emps = cur.fetchall()

In [11]:
for emp in emps:
    ssn, name, category, gross_sal, basic_sal = emp
    if category == "A":
        da = 80 / 100 * basic_sal
        gross_sal = basic_sal + da
        tax = 30 / 100 * gross_sal
    elif category == "B":
        da = 50 / 100 * basic_sal
        gross_sal = basic_sal + da
        tax = 20 / 100 * gross_sal
    elif category == "C":
        da = 30 / 100 * basic_sal
        gross_sal = basic_sal + da
        tax = 10 / 100 * gross_sal
    net_sal = basic_sal + da - tax
    
    cur.execute("update employee set gross_sal=? where ssn=?", 
                (gross_sal, ssn))
    
    print("name:", name, "ssn:", ssn, "net sal:", net_sal)

name: Rohan ssn: 1 net sal: 1260.0
name: Mohan ssn: 2 net sal: 2400.0
name: Sohan ssn: 3 net sal: 3510.0


In [12]:
cur.execute("select * from employee")
emps = cur.fetchall()
print(emps)

[(1, 'Rohan', 'A', 1800.0, 1000.0), (2, 'Mohan', 'B', 3000.0, 2000.0), (3, 'Sohan', 'C', 3900.0, 3000.0)]


In [13]:
con.commit()
con.close()

Implement Library management where students can borrow as well as donate books. Books table:

1 id INTEGER PRIMARY KEY 2 name TEXT 3 total_count INTEGER

a) Insert values to the table

34,king,5

123,Harry Potter,3

b) Update the table based on user inputs: based on book id I) BORROW II) RETURN

In [14]:
import sqlite3
con = sqlite3.connect("library.db")
cur = con.cursor()

In [16]:
cur.execute("""
    create table books(
        id integer primary key,
        name text,
        tcount integer
    )
""")

In [17]:
books = [
    (34, "king", 5),
    (123, "Harry Potter", 3)
]
cur.executemany("insert into books values (?, ?, ?)", books)

In [18]:
cur.execute("select * from books")
books = cur.fetchall()
print(books)

[(34, 'king', 5), (123, 'Harry Potter', 3)]


In [23]:
while 1:
    print("\n\nMenu \n1. borrow \n2. return \n3. exit")
    opt = int(input("\nEnter Option: "))
    if opt == 3:
        break
    book_id = int(input("Enter the book id: "))
    if opt == 1:
        cur.execute("update books set tcount = tcount - ? where id = ?", 
                    (1, book_id))
        print(book_id, "book borrowed")
    elif opt == 2:
        cur.execute("update books set tcount = tcount + ? where id = ?", 
                    (1, book_id))
        print(book_id, "book returned")
    else:
        print("Wrong input")



Menu 
1. borrow 
2. return 
3. exit

Enter Option: 1
Enter the book id: 34
34 book borrowed


Menu 
1. borrow 
2. return 
3. exit

Enter Option: 1
Enter the book id: 34
34 book borrowed


Menu 
1. borrow 
2. return 
3. exit

Enter Option: 2
Enter the book id: 123
123 book returned


Menu 
1. borrow 
2. return 
3. exit

Enter Option: 3


In [24]:
cur.execute("select * from books")
books = cur.fetchall()
print(books)

[(34, 'king', 3), (123, 'Harry Potter', 4)]


In [25]:
con.commit()
con.close()

#### see questions

In [26]:
# 2) a) b) both top

In [29]:
# 2) a)

In [47]:
import sqlite3
con = sqlite3.connect("companySEEQ.db")
cur = con.cursor()

In [36]:
cur.execute("""
    create table company(
        id integer, 
        name text, 
        age integer,
        address text, 
        salary real
    )
""")

In [37]:
employees = [
    (1, "paul", 32, "california", 20000.0),
    (2, "allen", 25, "texas", 15000.0),
    (3, "teddy", 23, "norway", 20000.0), 
    (4, "james", 44, "norway", 5000.0),
    (5, "james", 45, "texas", 5000.0)
]

cur.executemany("insert into company values (?, ?, ?, ?, ?)", employees)

In [42]:
# having should and must have group by statement
cur.execute("select * from company group by name having count(name) < 2")
print(cur.fetchall())

[(2, 'allen', 25, 'texas', 15000.0), (1, 'paul', 32, 'california', 20000.0), (3, 'teddy', 23, 'norway', 20000.0)]


In [44]:
cur.execute("""select name, sum(salary) from company group by name 
                order by name asc""")
print(cur.fetchall())

[('allen', 15000.0), ('james', 10000.0), ('paul', 20000.0), ('teddy', 20000.0)]


In [48]:
con.commit()
con.close()

SELECT column_name(s)
FROM table_name
WHERE condition
GROUP BY column_name(s)
HAVING condition
ORDER BY column_name(s);

# unit 3

In [51]:
import numpy as np

In [85]:
# np.random.seed(0)

### IMP

In [66]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(20, size=(3, 4))
x1, x2

(array([0, 2, 4, 0, 6, 2]),
 array([[ 5, 12,  5, 19],
        [ 8, 12, 16,  0],
        [18, 14,  9, 15]]))

In [67]:
x1.ndim, x1.shape, x1.size, x1.dtype, x1.itemsize, x1.nbytes

(1, (6,), 6, dtype('int32'), 4, 24)

In [68]:
x1[0], x1[3], x1[-1], x1[-2]

(0, 0, 2, 6)

In [69]:
x1[0] = 3.135678 # truncate
x1

array([3, 2, 4, 0, 6, 2])

In [70]:
x2[0, 0], x2[2, 0], x2[2, -1]

(5, 18, 15)

### IMP

In [86]:
x = np.arange(10)

In [72]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

# reverse

In [74]:
x[::-1] # reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
x[5::-2]

array([5, 3, 1])

In [78]:
x2[:3, ::2]

array([[ 5,  5],
       [ 8, 16],
       [18,  9]])

In [79]:
x2[:, 0], x2[0, :] # reduces dimension

(array([ 5,  8, 18]), array([ 5, 12,  5, 19]))

In [80]:
x2[0] # equivalent to x[0, :]

array([ 5, 12,  5, 19])

In [87]:
a = x2[:2, :2]
x2[0, 0] = 99999
x2, a

(array([[99999,    12,     5,    19],
        [    8,    12,    16,     0],
        [   18,    14,     9,    15]]),
 array([[99999,    12],
        [    8,    12]]))

### COPY

In [84]:
a = x2[:2, :2].copy()
x2[0, 0] = 8888888
a, x2

(array([[99999,    12],
        [    8,    12]]),
 array([[8888888,      12,       5,      19],
        [      8,      12,      16,       0],
        [     18,      14,       9,      15]]))

### IMP

In [89]:
a = np.arange(1, 10).reshape((3, 3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
x = np.array([1, 2, 3])

In [91]:
x.reshape((1, 3)), x[np.newaxis, :]

(array([[1, 2, 3]]), array([[1, 2, 3]]))

In [92]:
x.reshape((3, 1)), x[:, np.newaxis]

(array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]]))

### imp

In [98]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [99]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [100]:
# np.concatenate([x, y, z], axis=1) 
# cannot work as the arrays are itself one dimension, i.e axis 0

In [101]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [102]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
np.concatenate([a, a], axis=1) # 0 is rows, 1 is col, it grows outside
# axis is like indexing, 0 is the outter most dimension, then 1, then 2.. etc

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [108]:
np.vstack([y, a])

array([[3, 2, 1],
       [1, 2, 3],
       [4, 5, 6]])

### IMP

In [111]:
b = np.array([[99], [99]])
np.hstack([a, b])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### IMP

In [132]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1]) 
# MAKE EVERY list TO np.array BEFORE MANIPULATING IN numpy
x1, x2, x3 = np.split(x, [3, 5]) 
# if not specifying no. of splits, specify indexes where it should split
# can specify no. only when it can split it equally
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [133]:
np.split(x, 2) 
# MAKE SURE x IS AN np.array() for this to work with no., coz it gave error 
# without it

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [134]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### IMP hsplit and vspilt

In [135]:
np.hsplit(x, [1, 3])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [136]:
np.vsplit(x, [1, 3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [137]:
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [140]:
np.min(x3), x3.min()

(1, 1)

In [141]:
np.sort(x3), np.argsort(x3)

(array([1, 2, 3]), array([2, 1, 0], dtype=int64))

In [143]:
x3.sort()
x3 # inplace

array([1, 2, 3])

In [160]:
x3 = x3[::-1]
x3.argsort()

array([0, 1, 2], dtype=int64)

### To reverse the order of the names and display them in descending order, use the Python[::-1] notation.

In [161]:
import numpy as np
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])
reverse_sort_indices = np.argsort(persons)[::-1] 
print("The reverse sorted names are:", persons[reverse_sort_indices]) 
print("The revere sorted ages with respect to names are:", ages[reverse_sort_indices]) 
print("The reverse sorted heights with respect to names are:", heights[reverse_sort_indices])

The reverse sorted names are: ['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
The revere sorted ages with respect to names are: [ 5 37 12 34 13]
The reverse sorted heights with respect to names are: [0.5  1.68 1.2  1.76 1.25]


In [149]:
x = np.random.randint(10, size=(3, 4))
x

array([[6, 3, 9, 9],
       [9, 7, 5, 3],
       [1, 6, 8, 9]])

In [159]:
x.sort() # sorting columns wise, axis 1
x

array([ 2,  9, 18, 25, 36, 37, 38, 47, 58, 64, 67, 73, 78, 93, 98])

In [158]:
x = np.random.randint(100, size=15)
np.partition(x, 4) 

array([ 9,  2, 18, 25, 36, 37, 38, 47, 64, 67, 58, 73, 98, 78, 93])

In [167]:
np.zeros((3, 5)), np.ones((3, 5)), np.full((3, 5), 69) # FULL not FILL

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69]]))

NumPy Arrays advantages

1.Size - Numpy data structures take up less space

2.Performance - they have a need for speed and are faster than lists

1. NumPy uses much less memory to store data

2. NumPy Arrays are faster than Python List

In [170]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
c = np.prod([arr1, arr2], axis=0) # np.sum
c

array([ 5, 12, 21, 32])

In [171]:
np.cumsum(arr2), np.cumprod(arr2)

(array([ 5, 11, 18, 26], dtype=int32),
 array([   5,   30,  210, 1680], dtype=int32))

In [173]:
arr2 <= 7

array([ True,  True,  True, False])

### imp

In [174]:
np.count_nonzero(arr2 <= 7)

3

In [176]:
np.sum(arr2 <= 7) # **********************************

3

In [181]:
arr2[arr2 <= 7] # boolean arrays as masks, return 1d array of all true values

array([5, 6, 7])

In [185]:
# 3) a)
arr = np.arange(12).reshape(4, 3)
row = np.array([0, -1])
col = np.array([0, -1]) # IMP HAS TO BE np.array, OTHERWIZSE WON'T WORK
arr[row[:, np.newaxis], col]

array([[ 0,  2],
       [ 9, 11]])

In [186]:
# 3, b)
np.max(arr), np.min(arr)

(11, 0)

In [188]:
# 4) a) 

# unit 4 and 5

In [191]:
import pandas as pd

In [192]:
df = pd.read_csv("gapminder.tsv", sep='\t')

In [193]:
df.shape, df.columns, df.dtypes, df.info, df.head(), df.tail()

((1704, 6),
 Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object'),
 country       object
 continent     object
 year           int64
 lifeExp      float64
 pop            int64
 gdpPercap    float64
 dtype: object,
 <bound method DataFrame.info of           country continent  year  lifeExp       pop   gdpPercap
 0     Afghanistan      Asia  1952   28.801   8425333  779.445314
 1     Afghanistan      Asia  1957   30.332   9240934  820.853030
 2     Afghanistan      Asia  1962   31.997  10267083  853.100710
 3     Afghanistan      Asia  1967   34.020  11537966  836.197138
 4     Afghanistan      Asia  1972   36.088  13079460  739.981106
 ...           ...       ...   ...      ...       ...         ...
 1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
 1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
 1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
 1702     Zimbabwe    Africa  2002   39.989  11926563  672.

In [195]:
cdf = df['country']
cdf

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [198]:
cdf.head(10), cdf.tail(15)

(0    Afghanistan
 1    Afghanistan
 2    Afghanistan
 3    Afghanistan
 4    Afghanistan
 5    Afghanistan
 6    Afghanistan
 7    Afghanistan
 8    Afghanistan
 9    Afghanistan
 Name: country, dtype: object,
 1689      Zambia
 1690      Zambia
 1691      Zambia
 1692    Zimbabwe
 1693    Zimbabwe
 1694    Zimbabwe
 1695    Zimbabwe
 1696    Zimbabwe
 1697    Zimbabwe
 1698    Zimbabwe
 1699    Zimbabwe
 1700    Zimbabwe
 1701    Zimbabwe
 1702    Zimbabwe
 1703    Zimbabwe
 Name: country, dtype: object)

### IMP

In [199]:
cdf.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [200]:
subset = df[['country', "continent", "year"]]
subset

country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

### deprecated Subsetting Columns by Index Position Break in Pandas i.e df[[1]], df[[0, -1]]

### subsetting rows, loc, iloc

In [201]:
df.head()

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [203]:
df.loc[0]

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [204]:
df.loc[99]

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

In [205]:
# df.loc[-1] # won't work*********************8

In [206]:
df.loc[df.shape[0] - 1] # alternatively # series

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [207]:
df.tail(1) # dataframe

country continent  year  lifeExp       pop   gdpPercap
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [208]:
df.iloc[0], df.iloc[99], df.iloc[-1], df.iloc[1703]

(country      Afghanistan
 continent           Asia
 year                1952
 lifeExp           28.801
 pop              8425333
 gdpPercap     779.445314
 Name: 0, dtype: object,
 country      Bangladesh
 continent          Asia
 year               1967
 lifeExp          43.453
 pop            62821884
 gdpPercap    721.186086
 Name: 99, dtype: object,
 country        Zimbabwe
 continent        Africa
 year               2007
 lifeExp          43.487
 pop            12311143
 gdpPercap    469.709298
 Name: 1703, dtype: object,
 country        Zimbabwe
 continent        Africa
 year               2007
 lifeExp          43.487
 pop            12311143
 gdpPercap    469.709298
 Name: 1703, dtype: object)

In [209]:
df.iloc[df.shape[0] - 1] # THIS WILL WORK ONLY HERE COZ the index label
# starts from 0... if the index label starts from 101... then this
# method won't work

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [210]:
df.loc[0], df.head(1) # series, dataframe

(country      Afghanistan
 continent           Asia
 year                1952
 lifeExp           28.801
 pop              8425333
 gdpPercap     779.445314
 Name: 0, dtype: object,
        country continent  year  lifeExp      pop   gdpPercap
 0  Afghanistan      Asia  1952   28.801  8425333  779.445314)

### Subsetting Multiple Rows, works on both loc and iloc

but there's a difference

In [211]:
df.loc[[0, 99, 999]], df.iloc[[0, 99, 999]]

(         country continent  year  lifeExp       pop    gdpPercap
 0    Afghanistan      Asia  1952   28.801   8425333   779.445314
 99    Bangladesh      Asia  1967   43.453  62821884   721.186086
 999     Mongolia      Asia  1967   51.253   1149500  1226.041130,
          country continent  year  lifeExp       pop    gdpPercap
 0    Afghanistan      Asia  1952   28.801   8425333   779.445314
 99    Bangladesh      Asia  1967   43.453  62821884   721.186086
 999     Mongolia      Asia  1967   51.253   1149500  1226.041130)

### for one row it is Series and for more than one row it is DataFrame

In [212]:
print(df.loc[0], type(df.loc[0]), sep='\n\n', end='\n\n')
print(df.loc[[0, 99]], type(df.loc[[0, 99]]), sep='\n\n')

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

<class 'pandas.core.series.Series'>

        country continent  year  lifeExp       pop   gdpPercap
0   Afghanistan      Asia  1952   28.801   8425333  779.445314
99   Bangladesh      Asia  1967   43.453  62821884  721.186086

<class 'pandas.core.frame.DataFrame'>


# Combining column and row subsetting

df.loc/iloc[rows, columns]

for loc we can use only column names and not column indices

for iloc we can use only column indices and not column names

In [213]:
df.loc[:5, ['year', 'pop']]

year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460
5  1977  14880372

In [214]:
df.iloc[:5, [2, 4, -1]]

year       pop   gdpPercap
0  1952   8425333  779.445314
1  1957   9240934  820.853030
2  1962  10267083  853.100710
3  1967  11537966  836.197138
4  1972  13079460  739.981106

In [215]:
# r = list(range(0, 10))
# s = df.iloc[:, r] # r out of range will not work
# s

In [216]:
df.iloc[:5, :3]

country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [219]:
df.iloc[:5, 3:6], df.iloc[:5, 3:]

(   lifeExp       pop   gdpPercap
 0   28.801   8425333  779.445314
 1   30.332   9240934  820.853030
 2   31.997  10267083  853.100710
 3   34.020  11537966  836.197138
 4   36.088  13079460  739.981106,
    lifeExp       pop   gdpPercap
 0   28.801   8425333  779.445314
 1   30.332   9240934  820.853030
 2   31.997  10267083  853.100710
 3   34.020  11537966  836.197138
 4   36.088  13079460  739.981106)

In [220]:
df.iloc[:5, 0:6:2], df.iloc[:5, ::2]

(       country  year       pop
 0  Afghanistan  1952   8425333
 1  Afghanistan  1957   9240934
 2  Afghanistan  1962  10267083
 3  Afghanistan  1967  11537966
 4  Afghanistan  1972  13079460,
        country  year       pop
 0  Afghanistan  1952   8425333
 1  Afghanistan  1957   9240934
 2  Afghanistan  1962  10267083
 3  Afghanistan  1967  11537966
 4  Afghanistan  1972  13079460)

In [221]:
# Subsetting Rows and Columns, single values
df.loc[42, 'country'] # even with iloc

'Angola'

In [222]:
# Subsetting Multiple Rows and Columns, array of values
df.iloc[[0, 99, 999], [0, 3, 5]] # even with iloc

country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [223]:
# Subsetting Columns by Range
r = list(range(5))
s = df.iloc[:, r]
s

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

Combining column and row subsetting
df.loc/iloc[rows, columns]

In [224]:
# Slicing Columns, when slicing is used
subset = df.iloc[:, :3]
subset.head()

country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [225]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, index=ind)

In [226]:
df1 = make_df("AB", [1, 2])
df2 = make_df("AB", [3, 4])
df1, df2

(    A   B
 1  A1  B1
 2  A2  B2,
     A   B
 3  A3  B3
 4  A4  B4)

In [227]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [228]:
df1 = make_df("AB", [1, 2])
df2 = make_df("CD", [1, 2])
pd.concat([df1, df2])

A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2

In [229]:
df1 = make_df("ABC", [1, 2])
df2 = make_df("BCD", [1, 2])
pd.concat([df1, df2])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
1  NaN  B1  C1   D1
2  NaN  B2  C2   D2

In [230]:
df1 = make_df("ABC", [1, 2])
df2 = make_df("BCD", [1, 2])
pd.concat([df1, df2], join='inner')

B   C
1  B1  C1
2  B2  C2
1  B1  C1
2  B2  C2

In [231]:
df1 = make_df("ABC", [1, 2])
df2 = make_df("BCD", [1, 2])
pd.concat([df1, df2], ignore_index=True)

A   B   C    D
0   A1  B1  C1  NaN
1   A2  B2  C2  NaN
2  NaN  B1  C1   D1
3  NaN  B2  C2   D2

In [234]:
df1 = make_df("ABC", [1, 2])
df2 = make_df("BCD", [1, 2])
e = pd.concat([df1, df2], keys=['x', 'y'])
e, e.loc['x']

(       A   B   C    D
 x 1   A1  B1  C1  NaN
   2   A2  B2  C2  NaN
 y 1  NaN  B1  C1   D1
   2  NaN  B2  C2   D2,
     A   B   C    D
 1  A1  B1  C1  NaN
 2  A2  B2  C2  NaN)

In [236]:
df1.append(df2), df1

(     A   B   C    D
 1   A1  B1  C1  NaN
 2   A2  B2  C2  NaN
 1  NaN  B1  C1   D1
 2  NaN  B2  C2   D2,
     A   B   C
 1  A1  B1  C1
 2  A2  B2  C2)

In [237]:
df1.index, df1.values, df1.columns

(Int64Index([1, 2], dtype='int64'),
 array([['A1', 'B1', 'C1'],
        ['A2', 'B2', 'C2']], dtype=object),
 Index(['A', 'B', 'C'], dtype='object'))

In [239]:
df1.append(df2, sort=True) # sort columns

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
1  NaN  B1  C1   D1
2  NaN  B2  C2   D2

In [243]:
df1 = make_df("ABC", [1, 2])
df2 = make_df("BCD", [1, 2])
e = pd.concat([df1, df2], keys=['x', 'y'], axis=1)
e, e['x']

(    x           y        
     A   B   C   B   C   D
 1  A1  B1  C1  B1  C1  D1
 2  A2  B2  C2  B2  C2  D2,
     A   B   C
 1  A1  B1  C1
 2  A2  B2  C2)

In [244]:
df = pd.read_csv("weather_by_cities.csv")
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   2/1/2017  new york           36          7   Sunny
2   3/1/2017  new york           28         12    Snow
3   4/1/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   2/1/2017    mumbai           85         12     Fog
6   3/1/2017    mumbai           87         15     Fog
7   4/1/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   2/1/2017     paris           50         13  Cloudy
10  3/1/2017     paris           54          8  Cloudy
11  4/1/2017     paris           42         10  Cloudy

In [245]:
g = df.groupby("city")
g

In [246]:
for city, data in g:
    print(city, data)

mumbai         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  2/1/2017  mumbai           85         12    Fog
6  3/1/2017  mumbai           87         15    Fog
7  4/1/2017  mumbai           92          5   Rain
new york         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  2/1/2017  new york           36          7  Sunny
2  3/1/2017  new york           28         12   Snow
3  4/1/2017  new york           33          7  Sunny
paris          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   2/1/2017  paris           50         13  Cloudy
10  3/1/2017  paris           54          8  Cloudy
11  4/1/2017  paris           42         10  Cloudy


In [248]:
df2 = g.get_group("mumbai")
df2

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  2/1/2017  mumbai           85         12    Fog
6  3/1/2017  mumbai           87         15    Fog
7  4/1/2017  mumbai           92          5   Rain

In [249]:
g.max(), g.min(), g.describe(), g.mean(), g.size(), g.count()

(               day  temperature  windspeed  event
 city                                             
 mumbai    4/1/2017           92         15  Sunny
 new york  4/1/2017           36         12  Sunny
 paris     4/1/2017           54         20  Sunny,
                day  temperature  windspeed   event
 city                                              
 mumbai    1/1/2017           85          5     Fog
 new york  1/1/2017           28          6    Rain
 paris     1/1/2017           42          8  Cloudy,
          temperature                                                   \
                count   mean       std   min    25%   50%    75%   max   
 city                                                                    
 mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0   
 new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0   
 paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0   
 
          windspeed                  

In [250]:
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   2/1/2017  new york           36          7   Sunny
2   3/1/2017  new york           28         12    Snow
3   4/1/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   2/1/2017    mumbai           85         12     Fog
6   3/1/2017    mumbai           87         15     Fog
7   4/1/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   2/1/2017     paris           50         13  Cloudy
10  3/1/2017     paris           54          8  Cloudy
11  4/1/2017     paris           42         10  Cloudy

In [255]:
df.reindex(range(5, 17)) # some error

day    city  temperature  windspeed   event
5   2/1/2017  mumbai         85.0       12.0     Fog
6   3/1/2017  mumbai         87.0       15.0     Fog
7   4/1/2017  mumbai         92.0        5.0    Rain
8   1/1/2017   paris         45.0       20.0   Sunny
9   2/1/2017   paris         50.0       13.0  Cloudy
10  3/1/2017   paris         54.0        8.0  Cloudy
11  4/1/2017   paris         42.0       10.0  Cloudy
12       NaN     NaN          NaN        NaN     NaN
13       NaN     NaN          NaN        NaN     NaN
14       NaN     NaN          NaN        NaN     NaN
15       NaN     NaN          NaN        NaN     NaN
16       NaN     NaN          NaN        NaN     NaN

In [256]:
df.set_index(pd.Index(list(range(5, 17))))

day      city  temperature  windspeed   event
5   1/1/2017  new york           32          6    Rain
6   2/1/2017  new york           36          7   Sunny
7   3/1/2017  new york           28         12    Snow
8   4/1/2017  new york           33          7   Sunny
9   1/1/2017    mumbai           90          5   Sunny
10  2/1/2017    mumbai           85         12     Fog
11  3/1/2017    mumbai           87         15     Fog
12  4/1/2017    mumbai           92          5    Rain
13  1/1/2017     paris           45         20   Sunny
14  2/1/2017     paris           50         13  Cloudy
15  3/1/2017     paris           54          8  Cloudy
16  4/1/2017     paris           42         10  Cloudy

In [258]:
df = pd.read_csv("WEATHER_DATA.csv", parse_dates=['day'])
df

day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [259]:
df.set_index('day', inplace=True)

In [260]:
df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [262]:
df.isnull(), df.notnull(), df.dropna, df.fillna(0)

(            temperature  windspeed  event
 day                                      
 2017-01-01        False      False  False
 2017-01-04         True      False  False
 2017-01-05        False       True  False
 2017-01-06         True      False   True
 2017-01-07        False       True  False
 2017-01-08         True       True  False
 2017-01-09         True       True   True
 2017-01-10        False      False  False
 2017-01-11        False      False  False,
             temperature  windspeed  event
 day                                      
 2017-01-01         True       True   True
 2017-01-04        False       True   True
 2017-01-05         True      False   True
 2017-01-06        False       True  False
 2017-01-07         True      False   True
 2017-01-08        False      False   True
 2017-01-09        False      False  False
 2017-01-10         True       True   True
 2017-01-11         True       True   True,
 <bound method DataFrame.dropna of             tempe

In [263]:
df.dropna(axis='rows', how='any', thresh=2)

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [264]:
df.fillna(0), df.fillna(method='ffill'), df.fillna(method='bfill')

(            temperature  windspeed   event
 day                                       
 2017-01-01         32.0        6.0    Rain
 2017-01-04          0.0        9.0   Sunny
 2017-01-05         28.0        0.0    Snow
 2017-01-06          0.0        7.0       0
 2017-01-07         32.0        0.0    Rain
 2017-01-08          0.0        0.0   Sunny
 2017-01-09          0.0        0.0       0
 2017-01-10         34.0        8.0  Cloudy
 2017-01-11         40.0       12.0   Sunny,
             temperature  windspeed   event
 day                                       
 2017-01-01         32.0        6.0    Rain
 2017-01-04         32.0        9.0   Sunny
 2017-01-05         28.0        9.0    Snow
 2017-01-06         28.0        7.0    Snow
 2017-01-07         32.0        7.0    Rain
 2017-01-08         32.0        7.0   Sunny
 2017-01-09         32.0        7.0   Sunny
 2017-01-10         34.0        8.0  Cloudy
 2017-01-11         40.0       12.0   Sunny,
             temperature  wind

In [265]:
df.fillna(method='ffill', limit=1)

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [266]:
df.fillna({
    "temperature": 0
})

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          0.0        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          0.0        NaN   Sunny
2017-01-09          0.0        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [267]:
df.interpolate(method='time')

temperature  windspeed   event
day                                       
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [268]:
dt = pd.date_range("01-01-2017", "01-11-2017")
idx = pd.DatetimeIndex(dt) # not necessary
# dt, idx, df.reindex(idx)
df.reindex(dt)

temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [269]:
df.replace(np.nan, 0)

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [270]:
df.replace([np.nan, 8.0], value=99)

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04         99.0        9.0   Sunny
2017-01-05         28.0       99.0    Snow
2017-01-06         99.0        7.0      99
2017-01-07         32.0       99.0    Rain
2017-01-08         99.0       99.0   Sunny
2017-01-09         99.0       99.0      99
2017-01-10         34.0       99.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [273]:
df.replace({
    "temperature": 32.0,
    "windspeed": 6.0
}, 6969696)

temperature  windspeed   event
day                                       
2017-01-01    6969696.0  6969696.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07    6969696.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [274]:
df.replace({
    6969696: 88888,
    np.nan: 11111
})

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04      11111.0        9.0   Sunny
2017-01-05         28.0    11111.0    Snow
2017-01-06      11111.0        7.0   11111
2017-01-07         32.0    11111.0    Rain
2017-01-08      11111.0    11111.0   Sunny
2017-01-09      11111.0    11111.0   11111
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [275]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})

In [276]:
df3 = pd.merge(df1, df2)
df4 = pd.concat([df1, df2])
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [277]:
df4

employee        group  hire_date
0      Bob   Accounting        NaN
1     Jake  Engineering        NaN
2     Lisa  Engineering        NaN
3      Sue           HR        NaN
0     Lisa          NaN     2004.0
1      Bob          NaN     2008.0
2     Jake          NaN     2012.0
3      Sue          NaN     2014.0

In [278]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [279]:
pd.merge(df3, df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [280]:
df.mode()

temperature  windspeed  event
0         32.0        6.0  Sunny
1          NaN        7.0    NaN
2          NaN        8.0    NaN
3          NaN        9.0    NaN
4          NaN       12.0    NaN