In [1]:
import numpy as np

## fancy indexing

## combined indexing

In [4]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
x[2, [2, 0, 1]]

array([10,  8,  9])

In [5]:
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [6]:
x[:, np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [27]:
print(x)
mask = np.array([1, 0, 1, 0], dtype=bool)
row = np.array([0, 2])
print(row[:, np.newaxis])
x[row[:, np.newaxis], mask]

# row[np.newaxis, :]
# x[row, mask]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [2]]


array([[ 0,  2],
       [ 8, 10]])